### ISSUE TITLE
Check of the dimension of anti-windup matrix wrong

### ISSUE THREAD

**Issue by nicolapedrocchi** [CNR-STIIMA-IRAS/eigen_control_toolbox#1]
Hi, I guess that the check of the antiwindup matrix is wrong. 

> Warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
     if ( (!aw_gain.cols()==m_nout) || (!aw_gain.rows()==m_nin)) 

In branch "nicola" a possible solution is proposed.

**Comment by ManuelBeschi** [comment]
Thanks, I fixed it
